In [2]:
import numpy as np

# 1.[簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？


In [4]:
a=np.arange(15).reshape(3, 5)
print('list(a): ', list(a))
print('tolist(): ', a.tolist())

list(a):  [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
tolist():  [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]


In [ ]:
list(a) 只會把第一層的元素轉換成 List

tolist() 全部都轉成list

# 2. 請試著在程式中印出以下三個 NdArray 的屬性？
（屬性：ndim、shape、size、dtype、itemsize、length、type）

In [15]:
a = np.random.randint(10, size=6) 
print(a)
print(a.ndim) #一維度空間
print(a.shape) #六乘一的矩陣維度
print(a.size) #總共有六個元素
print(a.dtype) #矩陣中的資料型態
print(a.itemsize) #每個元素占用的空間
print(a.data) #資料儲存在哪

[6 0 1 0 4 7]
1
(6,)
6
int32
4


In [17]:
b = np.random.randint(10, size=(3,4)) 
print(b)
print(b.ndim) #二維度空間
print(b.shape) #三乘四的矩陣維度
print(b.size) #總共有十二個元素
print(b.dtype) #矩陣中的資料型態
print(b.itemsize) #每個元素占用的空間
print(b.data) #資料儲存在哪

[[8 0 2 5]
 [3 4 1 5]
 [9 8 0 5]]
2
(3, 4)
12
int32
4


In [16]:
c = np.random.randint(10, size=(2,3,2)) 
print(c)
print(c.ndim) #三維度空間
print(c.shape) #二乘三乘二的矩陣維度
print(c.size) #總共有十二個元素
print(c.dtype) #矩陣中的資料型態
print(c.itemsize) #每個元素占用的空間
print(c.data) #資料儲存在哪

[[[2 2]
  [2 0]
  [7 4]]

 [[1 7]
  [1 6]
  [6 7]]]
3
(2, 3, 2)
12
int32
4


# 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [25]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))

[4, 6, 7, 3, 8, 2]
[4, 6, 7, 3, 8, 2]


In [26]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))

[[5, 7, 6, 2], [2, 6, 9, 7], [1, 3, 8, 7]]
[array([5, 7, 6, 2]), array([2, 6, 9, 7]), array([1, 3, 8, 7])]


In [27]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))

[[[6, 4], [6, 8], [0, 0]], [[4, 9], [1, 4], [7, 5]]]
[array([[6, 4],
       [6, 8],
       [0, 0]]), array([[4, 9],
       [1, 4],
       [7, 5]])]


In [29]:
def tolist(iterable):
    for it in iterable:
        return it.tolist()
print(a)
print(b)
print(c)

[4 6 7 3 8 2]
[[5 7 6 2]
 [2 6 9 7]
 [1 3 8 7]]
[[[6 4]
  [6 8]
  [0 0]]

 [[4 9]
  [1 4]
  [7 5]]]
